apiVersion: apps/v1
kind: Deployment
metadata:
  name: mom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mom
  template:
    metadata:
      labels:
        app: mom
    spec:
      containers:
      - name: mom
        image: fabiocalt/mom-server
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: mom
spec:
  selector:
    app: mom
  ports:
  - port: 8000
    targetPort: 8000

