apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-subscriber
  template:
    metadata:
      labels:
        app: nats-subscriber
    spec:
      containers:
      - name: subscriber
        image: fabiocalt/qosnatsimage
        imagePullPolicy: Always

