apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - name: controller
        image: fabiocalt/controller:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: controller-service
spec:
  selector:
    app: controller
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP

